defmodule NebulithWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :nebulith

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_nebulith_key",
    signing_salt: "nGvs9VRq",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # CORS runs FIRST, before Plug.Static.
  #
  # It used to sit just above the Router, at the bottom of this pipeline, which meant the API got its
  # `access-control-allow-origin` header (the API goes through the Router) and the baked tile PNGs did NOT
  # (Plug.Static answers and HALTS long before the bottom of the pipeline is reached).
  #
  # The consequence was not a failed request, the images loaded fine, but a TAINTED canvas: a cross-origin
  # image drawn into a canvas without CORS makes that canvas unreadable, so `getImageData` and `toDataURL`
  # throw a SecurityError on anything the map is drawn into. That blocks reading pixels back for a level
  # minimap, for cached preset thumbnails, and for any in-browser pixel test.
  #
  # The frontend's half of this is `crossOrigin = 'anonymous'` on the tile images; both halves are required.
  #
  # Open to any origin on purpose: the engine is meant to be embeddable, so a page on any host can
  # frame it and its bundle can read this API. Nothing here is authenticated, and /admin is Basic auth
  # over a browser navigation rather than an XHR, so a wildcard costs nothing it was protecting.
  plug CORSPlug, origin: "*"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :nebulith,
    gzip: not code_reloading?,
    only: NebulithWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :nebulith
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  # THE TEST'S OWN DATABASE TRANSACTION, joined by the browser. An end-to-end test drives a real browser, so
  # its requests arrive on a DIFFERENT process from the test and would otherwise see an empty database rather
  # than what the test set up. `PhoenixTest.Playwright` sends the sandbox metadata on the user agent and this
  # reads it. Test only, and a no-op without the header.
  if Mix.env() == :test do
    # No `header:` option on purpose: the metadata rides the USER AGENT, which is what PhoenixTest.Playwright
    # sends and what this plug reads by default. Naming a custom header made it look for one nobody sends, so
    # the browser's requests opened their own connection and saw an empty database.
    plug Phoenix.Ecto.SQL.Sandbox,
      at: "/sandbox",
      repo: Nebulith.Repo,
      sandbox: Ecto.Adapters.SQL.Sandbox
  end

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug NebulithWeb.Router
end
