defmodule NebulithWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :nebulith

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_nebulith_key",
    signing_salt: "nGvs9VRq",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # CORS runs FIRST, before Plug.Static.
  #
  # It used to sit just above the Router, at the bottom of this pipeline, which meant the API got its
  # `access-control-allow-origin` header (the API goes through the Router) and the baked tile PNGs did NOT
  # (Plug.Static answers and HALTS long before the bottom of the pipeline is reached).
  #
  # The consequence was not a failed request, the images loaded fine, but a TAINTED canvas: a cross-origin
  # image drawn into a canvas without CORS makes that canvas unreadable, so `getImageData` and `toDataURL`
  # throw a SecurityError on anything the map is drawn into. That blocks reading pixels back for a level
  # minimap, for cached preset thumbnails, and for any in-browser pixel test.
  #
  # The frontend's half of this is `crossOrigin = 'anonymous'` on the tile images; both halves are required.
  plug CORSPlug, origin: [~r/^http:\/\/localhost:\d+$/]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :nebulith,
    gzip: not code_reloading?,
    only: NebulithWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :nebulith
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug NebulithWeb.Router
end
