/**
 * TEMPLATE PRESETS — pure data for the random-map generator
 *
 * Extracted verbatim from the game-engine templates page. Categorized by
 * Size (S/M/L) × Theme × Type (exterior/interior). No runtime deps — pure
 * config literals + their supporting types.
 */
// ═══════════════════════════════════════════════════════════════════
// TEMPLATE PRESET SYSTEM
// Categorized by: Size (S/M/L) × Theme × Type (exterior/interior)
// ═══════════════════════════════════════════════════════════════════

export type TemplateSize = 'small' | 'medium' | 'large'
export type TemplateTheme =
  | 'village' | 'forest' | 'castle' | 'ice' | 'desert' | 'dungeon'
  | 'volcanic' | 'cave' | 'crypt' | 'underwater' | 'temple'
  | 'italian' | 'chinese' | 'spanish' | 'russian' | 'japanese'
  | 'egyptian' | 'african' | 'venezuelan' | 'peruvian' | 'argentinian'
  | 'american' | 'mexican' | 'australian'
export type TemplateType = 'exterior' | 'interior'

export interface TemplatePreset {
  id: string
  name: string
  description: string
  size: TemplateSize
  theme: TemplateTheme
  type: TemplateType
  // Grid dimensions
  cols: { min: number; max: number }
  rows: { min: number; max: number }
  // Road system
  roads: {
    enabled: boolean
    pattern: 'grid' | 'cross' | 'winding' | 'single' | 'none'
    width: number // 1-3
  }
  // Water features
  water: {
    type: 'river' | 'lake' | 'ocean' | 'moat' | 'none'
    coverage: number // 0-1
  }
  // Buildings
  buildings: {
    count: { min: number; max: number }
    types: ('house' | 'shop' | 'tower' | 'castle' | 'hut')[]
    hasPlaza: boolean
  }
  // Nature
  nature: {
    treeDensity: number // 0-1
    bushDensity: number // 0-1
    flowerDensity: number // 0-1
    rockDensity: number // 0-1
  }
  // NPCs
  npcs: {
    enabled: boolean
    count: { min: number; max: number }
  }
  // Ground colors
  groundType: 'grass' | 'stone' | 'sand' | 'snow' | 'wood'
  // Walls (for interiors)
  walls?: {
    enabled: boolean
    thickness: number
  }
}

export const TEMPLATE_PRESETS: Record<string, TemplatePreset> = {
  // ─── VILLAGES ─────────────────────────────────────────────────────
  'village-small': {
    id: 'village-small',
    name: 'Small Town',
    description: 'Cozy small town with a few houses',
    size: 'small',
    theme: 'village',
    type: 'exterior',
    cols: { min: 30, max: 40 },
    rows: { min: 30, max: 40 },
    roads: { enabled: true, pattern: 'cross', width: 2 },
    water: { type: 'lake', coverage: 0.05 },
    buildings: { count: { min: 3, max: 5 }, types: ['house', 'shop'], hasPlaza: true },
    nature: { treeDensity: 0.25, bushDensity: 0.1, flowerDensity: 0.05, rockDensity: 0.02 },
    npcs: { enabled: true, count: { min: 2, max: 4 } },
    groundType: 'grass',
  },
  'village-medium': {
    id: 'village-medium',
    name: 'Town',
    description: 'Bustling town with markets and homes',
    size: 'medium',
    theme: 'village',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'grid', width: 2 },
    water: { type: 'river', coverage: 0.08 },
    buildings: { count: { min: 6, max: 10 }, types: ['house', 'shop', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.2, bushDensity: 0.08, flowerDensity: 0.04, rockDensity: 0.02 },
    npcs: { enabled: true, count: { min: 4, max: 8 } },
    groundType: 'grass',
  },
  'village-large': {
    id: 'village-large',
    name: 'City',
    description: 'Large city with districts',
    size: 'large',
    theme: 'village',
    type: 'exterior',
    cols: { min: 80, max: 100 },
    rows: { min: 80, max: 100 },
    roads: { enabled: true, pattern: 'grid', width: 3 },
    water: { type: 'river', coverage: 0.1 },
    buildings: { count: { min: 12, max: 20 }, types: ['house', 'shop', 'tower', 'castle'], hasPlaza: true },
    nature: { treeDensity: 0.15, bushDensity: 0.05, flowerDensity: 0.03, rockDensity: 0.01 },
    npcs: { enabled: true, count: { min: 8, max: 15 } },
    groundType: 'grass',
  },

  // ─── FORESTS ──────────────────────────────────────────────────────
  'forest-small': {
    id: 'forest-small',
    name: 'Forest Clearing',
    description: 'Small woodland area',
    size: 'small',
    theme: 'forest',
    type: 'exterior',
    cols: { min: 30, max: 40 },
    rows: { min: 30, max: 40 },
    roads: { enabled: true, pattern: 'winding', width: 1 },
    water: { type: 'lake', coverage: 0.08 },
    buildings: { count: { min: 0, max: 1 }, types: ['hut'], hasPlaza: false },
    nature: { treeDensity: 0.5, bushDensity: 0.2, flowerDensity: 0.08, rockDensity: 0.05 },
    npcs: { enabled: false, count: { min: 0, max: 1 } },
    groundType: 'grass',
  },
  'forest-large': {
    id: 'forest-large',
    name: 'Deep Woods',
    description: 'Dense forest with hidden paths',
    size: 'large',
    theme: 'forest',
    type: 'exterior',
    cols: { min: 70, max: 90 },
    rows: { min: 70, max: 90 },
    roads: { enabled: true, pattern: 'winding', width: 1 },
    water: { type: 'river', coverage: 0.1 },
    buildings: { count: { min: 1, max: 3 }, types: ['hut', 'tower'], hasPlaza: false },
    nature: { treeDensity: 0.6, bushDensity: 0.25, flowerDensity: 0.1, rockDensity: 0.08 },
    npcs: { enabled: true, count: { min: 1, max: 3 } },
    groundType: 'grass',
  },

  // ─── CASTLES ──────────────────────────────────────────────────────
  'castle-exterior': {
    id: 'castle-exterior',
    name: 'Castle Grounds',
    description: 'Fortified castle with courtyard',
    size: 'large',
    theme: 'castle',
    type: 'exterior',
    cols: { min: 60, max: 80 },
    rows: { min: 60, max: 80 },
    roads: { enabled: true, pattern: 'cross', width: 3 },
    water: { type: 'moat', coverage: 0.15 },
    buildings: { count: { min: 4, max: 8 }, types: ['castle', 'tower', 'house'], hasPlaza: true },
    nature: { treeDensity: 0.1, bushDensity: 0.05, flowerDensity: 0.02, rockDensity: 0.03 },
    npcs: { enabled: true, count: { min: 4, max: 8 } },
    groundType: 'grass',
  },
  'castle-interior': {
    id: 'castle-interior',
    name: 'Castle Hall',
    description: 'Grand interior hall',
    size: 'medium',
    theme: 'castle',
    type: 'interior',
    cols: { min: 25, max: 35 },
    rows: { min: 20, max: 30 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0.02, rockDensity: 0 },
    npcs: { enabled: true, count: { min: 2, max: 5 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },

  // ─── ICE THEME ────────────────────────────────────────────────────
  'ice-village': {
    id: 'ice-village',
    name: 'Frozen Village',
    description: 'Snow-covered settlement',
    size: 'medium',
    theme: 'ice',
    type: 'exterior',
    cols: { min: 45, max: 60 },
    rows: { min: 45, max: 60 },
    roads: { enabled: true, pattern: 'cross', width: 2 },
    water: { type: 'lake', coverage: 0.1 }, // Frozen lake
    buildings: { count: { min: 4, max: 7 }, types: ['house', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.15, bushDensity: 0.05, flowerDensity: 0, rockDensity: 0.08 },
    npcs: { enabled: true, count: { min: 2, max: 5 } },
    groundType: 'snow',
  },
  'ice-castle-interior': {
    id: 'ice-castle-interior',
    name: 'Ice Castle Interior',
    description: 'Frozen throne room',
    size: 'large',
    theme: 'ice',
    type: 'interior',
    cols: { min: 35, max: 50 },
    rows: { min: 30, max: 45 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0, rockDensity: 0.05 },
    npcs: { enabled: true, count: { min: 1, max: 4 } },
    groundType: 'snow',
    walls: { enabled: true, thickness: 3 },
  },

  // ─── DESERT ───────────────────────────────────────────────────────
  'desert-oasis': {
    id: 'desert-oasis',
    name: 'Desert Oasis',
    description: 'Sandy area with water source',
    size: 'medium',
    theme: 'desert',
    type: 'exterior',
    cols: { min: 45, max: 60 },
    rows: { min: 45, max: 60 },
    roads: { enabled: true, pattern: 'winding', width: 1 },
    water: { type: 'lake', coverage: 0.12 },
    buildings: { count: { min: 2, max: 5 }, types: ['house', 'shop'], hasPlaza: true },
    nature: { treeDensity: 0.08, bushDensity: 0.1, flowerDensity: 0.02, rockDensity: 0.15 },
    npcs: { enabled: true, count: { min: 2, max: 4 } },
    groundType: 'sand',
  },

  // ─── DUNGEONS ─────────────────────────────────────────────────────
  'dungeon-small': {
    id: 'dungeon-small',
    name: 'Dungeon Room',
    description: 'Single dungeon chamber',
    size: 'small',
    theme: 'dungeon',
    type: 'interior',
    cols: { min: 20, max: 25 },
    rows: { min: 20, max: 25 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0, rockDensity: 0.1 },
    npcs: { enabled: true, count: { min: 1, max: 3 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },
  'dungeon-large': {
    id: 'dungeon-large',
    name: 'Dungeon Complex',
    description: 'Multi-room dungeon',
    size: 'large',
    theme: 'dungeon',
    type: 'interior',
    cols: { min: 50, max: 70 },
    rows: { min: 50, max: 70 },
    roads: { enabled: true, pattern: 'grid', width: 2 }, // Corridors
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0, rockDensity: 0.08 },
    npcs: { enabled: true, count: { min: 3, max: 8 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 1 },
  },

  // ─── FROZEN ENVIRONMENTS ──────────────────────────────────────────
  'frozen-forest': {
    id: 'frozen-forest',
    name: 'Frozen Forest',
    description: 'Snow-covered woods with frosted trees and ice patches',
    size: 'medium',
    theme: 'ice',
    type: 'exterior',
    cols: { min: 50, max: 70 },
    rows: { min: 50, max: 70 },
    roads: { enabled: true, pattern: 'winding', width: 1 },
    water: { type: 'lake', coverage: 0.08 },
    buildings: { count: { min: 0, max: 2 }, types: ['hut'], hasPlaza: false },
    nature: { treeDensity: 0.4, bushDensity: 0.1, flowerDensity: 0, rockDensity: 0.1 },
    npcs: { enabled: false, count: { min: 0, max: 1 } },
    groundType: 'snow',
  },
  'frozen-cave': {
    id: 'frozen-cave',
    name: 'Frozen Cave',
    description: 'Ice walls with frozen stalactites',
    size: 'medium',
    theme: 'cave',
    type: 'interior',
    cols: { min: 35, max: 50 },
    rows: { min: 35, max: 50 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'lake', coverage: 0.05 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0, rockDensity: 0.15 },
    npcs: { enabled: true, count: { min: 1, max: 3 } },
    groundType: 'snow',
    walls: { enabled: true, thickness: 2 },
  },

  // ─── VOLCANIC ENVIRONMENTS ────────────────────────────────────────
  'volcanic-cave': {
    id: 'volcanic-cave',
    name: 'Volcanic Cave',
    description: 'Lava flows through obsidian chambers',
    size: 'medium',
    theme: 'volcanic',
    type: 'interior',
    cols: { min: 40, max: 55 },
    rows: { min: 40, max: 55 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'river', coverage: 0.12 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0, rockDensity: 0.2 },
    npcs: { enabled: true, count: { min: 1, max: 3 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },
  'volcanic-zone': {
    id: 'volcanic-zone',
    name: 'Volcanic Zone',
    description: 'Ash-covered ground with lava rivers',
    size: 'large',
    theme: 'volcanic',
    type: 'exterior',
    cols: { min: 60, max: 80 },
    rows: { min: 60, max: 80 },
    roads: { enabled: true, pattern: 'winding', width: 2 },
    water: { type: 'river', coverage: 0.15 },
    buildings: { count: { min: 1, max: 3 }, types: ['tower'], hasPlaza: false },
    nature: { treeDensity: 0.05, bushDensity: 0.02, flowerDensity: 0, rockDensity: 0.25 },
    npcs: { enabled: true, count: { min: 1, max: 3 } },
    groundType: 'stone',
  },
  'volcano-interior': {
    id: 'volcano-interior',
    name: 'Volcano Interior',
    description: 'Molten rock and fire-lit obsidian halls',
    size: 'large',
    theme: 'volcanic',
    type: 'interior',
    cols: { min: 50, max: 70 },
    rows: { min: 50, max: 70 },
    roads: { enabled: true, pattern: 'cross', width: 3 },
    water: { type: 'river', coverage: 0.2 },
    buildings: { count: { min: 0, max: 1 }, types: ['tower'], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0, rockDensity: 0.15 },
    npcs: { enabled: true, count: { min: 2, max: 5 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 3 },
  },

  // ─── CAVE ENVIRONMENTS ────────────────────────────────────────────
  'ancient-cave': {
    id: 'ancient-cave',
    name: 'Ancient Cave',
    description: 'Moss-covered stone with glowing runes',
    size: 'medium',
    theme: 'cave',
    type: 'interior',
    cols: { min: 40, max: 55 },
    rows: { min: 40, max: 55 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'lake', coverage: 0.05 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0.05, flowerDensity: 0.02, rockDensity: 0.12 },
    npcs: { enabled: true, count: { min: 1, max: 3 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },
  'forest-cave': {
    id: 'forest-cave',
    name: 'Forest Cave',
    description: 'Tree roots and mushrooms in earthen tunnels',
    size: 'small',
    theme: 'cave',
    type: 'interior',
    cols: { min: 25, max: 35 },
    rows: { min: 25, max: 35 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0.1, bushDensity: 0.15, flowerDensity: 0.1, rockDensity: 0.08 },
    npcs: { enabled: true, count: { min: 0, max: 2 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },
  'underground-cave': {
    id: 'underground-cave',
    name: 'Underground Cave',
    description: 'Deep caverns with crystals and rock formations',
    size: 'large',
    theme: 'cave',
    type: 'interior',
    cols: { min: 55, max: 75 },
    rows: { min: 55, max: 75 },
    roads: { enabled: true, pattern: 'winding', width: 2 },
    water: { type: 'river', coverage: 0.08 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0.02, flowerDensity: 0.05, rockDensity: 0.2 },
    npcs: { enabled: true, count: { min: 2, max: 5 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },

  // ─── CRYPT & CEMETERY ─────────────────────────────────────────────
  'crypt': {
    id: 'crypt',
    name: 'Crypt',
    description: 'Stone floors with coffins and flickering candles',
    size: 'small',
    theme: 'crypt',
    type: 'interior',
    cols: { min: 20, max: 30 },
    rows: { min: 20, max: 30 },
    roads: { enabled: false, pattern: 'none', width: 0 },
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 0, max: 0 }, types: [], hasPlaza: false },
    nature: { treeDensity: 0, bushDensity: 0, flowerDensity: 0, rockDensity: 0.05 },
    npcs: { enabled: true, count: { min: 1, max: 3 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },
  'cemetery': {
    id: 'cemetery',
    name: 'Cemetery',
    description: 'Graves, dead grass, and iron fences',
    size: 'medium',
    theme: 'crypt',
    type: 'exterior',
    cols: { min: 40, max: 55 },
    rows: { min: 40, max: 55 },
    roads: { enabled: true, pattern: 'grid', width: 1 },
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 1, max: 3 }, types: ['hut', 'tower'], hasPlaza: false },
    nature: { treeDensity: 0.15, bushDensity: 0.05, flowerDensity: 0.02, rockDensity: 0.15 },
    npcs: { enabled: true, count: { min: 1, max: 4 } },
    groundType: 'grass',
  },

  // ─── UNDERWATER & TEMPLE ──────────────────────────────────────────
  'underwater-temple': {
    id: 'underwater-temple',
    name: 'Underwater Temple',
    description: 'Coral, seaweed, and ancient submerged ruins',
    size: 'large',
    theme: 'underwater',
    type: 'interior',
    cols: { min: 50, max: 70 },
    rows: { min: 50, max: 70 },
    roads: { enabled: true, pattern: 'cross', width: 2 },
    water: { type: 'none', coverage: 0 },
    buildings: { count: { min: 2, max: 5 }, types: ['tower', 'castle'], hasPlaza: true },
    nature: { treeDensity: 0.1, bushDensity: 0.2, flowerDensity: 0.15, rockDensity: 0.1 },
    npcs: { enabled: true, count: { min: 2, max: 5 } },
    groundType: 'stone',
    walls: { enabled: true, thickness: 2 },
  },
  'forest-temple': {
    id: 'forest-temple',
    name: 'Forest Temple',
    description: 'Overgrown stone ruins with vines and moss',
    size: 'medium',
    theme: 'temple',
    type: 'exterior',
    cols: { min: 45, max: 60 },
    rows: { min: 45, max: 60 },
    roads: { enabled: true, pattern: 'cross', width: 2 },
    water: { type: 'lake', coverage: 0.05 },
    buildings: { count: { min: 3, max: 6 }, types: ['tower', 'castle'], hasPlaza: true },
    nature: { treeDensity: 0.35, bushDensity: 0.2, flowerDensity: 0.1, rockDensity: 0.1 },
    npcs: { enabled: true, count: { min: 1, max: 4 } },
    groundType: 'grass',
  },

  // ─── EGYPTIAN THEME ───────────────────────────────────────────────
  'egyptian-desert': {
    id: 'egyptian-desert',
    name: 'Egyptian Desert',
    description: 'Sand dunes with pyramids and sphinx decorations',
    size: 'large',
    theme: 'egyptian',
    type: 'exterior',
    cols: { min: 60, max: 80 },
    rows: { min: 60, max: 80 },
    roads: { enabled: true, pattern: 'cross', width: 2 },
    water: { type: 'river', coverage: 0.08 },
    buildings: { count: { min: 4, max: 8 }, types: ['tower', 'castle'], hasPlaza: true },
    nature: { treeDensity: 0.05, bushDensity: 0.03, flowerDensity: 0.01, rockDensity: 0.12 },
    npcs: { enabled: true, count: { min: 3, max: 7 } },
    groundType: 'sand',
  },

  // ─── CULTURAL THEMES ──────────────────────────────────────────────
  'italian-village': {
    id: 'italian-village',
    name: 'Italian Village',
    description: 'Terracotta, olive trees, and Roman columns',
    size: 'medium',
    theme: 'italian',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'grid', width: 2 },
    water: { type: 'lake', coverage: 0.05 },
    buildings: { count: { min: 5, max: 10 }, types: ['house', 'shop', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.2, bushDensity: 0.08, flowerDensity: 0.06, rockDensity: 0.03 },
    npcs: { enabled: true, count: { min: 4, max: 8 } },
    groundType: 'grass',
  },
  'chinese-village': {
    id: 'chinese-village',
    name: 'Chinese Village',
    description: 'Red and gold pagodas with lanterns',
    size: 'medium',
    theme: 'chinese',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'grid', width: 2 },
    water: { type: 'lake', coverage: 0.08 },
    buildings: { count: { min: 5, max: 10 }, types: ['house', 'shop', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.2, bushDensity: 0.1, flowerDensity: 0.08, rockDensity: 0.04 },
    npcs: { enabled: true, count: { min: 4, max: 8 } },
    groundType: 'grass',
  },
  'spanish-village': {
    id: 'spanish-village',
    name: 'Spanish Village',
    description: 'White walls, orange roofs, and courtyards',
    size: 'medium',
    theme: 'spanish',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'grid', width: 2 },
    water: { type: 'lake', coverage: 0.04 },
    buildings: { count: { min: 6, max: 12 }, types: ['house', 'shop', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.15, bushDensity: 0.1, flowerDensity: 0.08, rockDensity: 0.02 },
    npcs: { enabled: true, count: { min: 5, max: 10 } },
    groundType: 'grass',
  },
  'russian-village': {
    id: 'russian-village',
    name: 'Russian Village',
    description: 'Onion domes, snow, and birch trees',
    size: 'medium',
    theme: 'russian',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'cross', width: 2 },
    water: { type: 'lake', coverage: 0.06 },
    buildings: { count: { min: 5, max: 9 }, types: ['house', 'shop', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.25, bushDensity: 0.05, flowerDensity: 0.02, rockDensity: 0.05 },
    npcs: { enabled: true, count: { min: 3, max: 7 } },
    groundType: 'snow',
  },
  'japanese-village': {
    id: 'japanese-village',
    name: 'Japanese Village',
    description: 'Cherry blossoms, torii gates, and bamboo',
    size: 'medium',
    theme: 'japanese',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'grid', width: 2 },
    water: { type: 'lake', coverage: 0.1 },
    buildings: { count: { min: 5, max: 10 }, types: ['house', 'shop', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.25, bushDensity: 0.1, flowerDensity: 0.15, rockDensity: 0.05 },
    npcs: { enabled: true, count: { min: 4, max: 8 } },
    groundType: 'grass',
  },
  'african-village': {
    id: 'african-village',
    name: 'African Village',
    description: 'Savanna grass, acacia trees, and mud huts',
    size: 'medium',
    theme: 'african',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'winding', width: 2 },
    water: { type: 'lake', coverage: 0.06 },
    buildings: { count: { min: 4, max: 8 }, types: ['hut', 'house'], hasPlaza: true },
    nature: { treeDensity: 0.15, bushDensity: 0.12, flowerDensity: 0.04, rockDensity: 0.08 },
    npcs: { enabled: true, count: { min: 4, max: 8 } },
    groundType: 'sand',
  },
  'venezuelan-village': {
    id: 'venezuelan-village',
    name: 'Venezuelan Village',
    description: 'Tropical paradise with colorful houses and palms',
    size: 'medium',
    theme: 'venezuelan',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'grid', width: 2 },
    water: { type: 'river', coverage: 0.08 },
    buildings: { count: { min: 5, max: 10 }, types: ['house', 'shop'], hasPlaza: true },
    nature: { treeDensity: 0.3, bushDensity: 0.15, flowerDensity: 0.12, rockDensity: 0.03 },
    npcs: { enabled: true, count: { min: 5, max: 10 } },
    groundType: 'grass',
  },
  'peruvian-village': {
    id: 'peruvian-village',
    name: 'Peruvian Village',
    description: 'Mountain village with llamas and ancient stones',
    size: 'medium',
    theme: 'peruvian',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'winding', width: 2 },
    water: { type: 'river', coverage: 0.05 },
    buildings: { count: { min: 4, max: 8 }, types: ['hut', 'house', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.1, bushDensity: 0.1, flowerDensity: 0.05, rockDensity: 0.2 },
    npcs: { enabled: true, count: { min: 3, max: 7 } },
    groundType: 'grass',
  },
  'argentinian-village': {
    id: 'argentinian-village',
    name: 'Argentinian Estancia',
    description: 'Pampas grass and ranch buildings',
    size: 'large',
    theme: 'argentinian',
    type: 'exterior',
    cols: { min: 60, max: 80 },
    rows: { min: 60, max: 80 },
    roads: { enabled: true, pattern: 'cross', width: 2 },
    water: { type: 'lake', coverage: 0.04 },
    buildings: { count: { min: 4, max: 8 }, types: ['house', 'hut'], hasPlaza: false },
    nature: { treeDensity: 0.12, bushDensity: 0.08, flowerDensity: 0.05, rockDensity: 0.03 },
    npcs: { enabled: true, count: { min: 3, max: 6 } },
    groundType: 'grass',
  },
  'american-frontier': {
    id: 'american-frontier',
    name: 'American Frontier',
    description: 'Wooden frontier town on the prairies',
    size: 'medium',
    theme: 'american',
    type: 'exterior',
    cols: { min: 50, max: 70 },
    rows: { min: 50, max: 70 },
    roads: { enabled: true, pattern: 'single', width: 3 },
    water: { type: 'river', coverage: 0.05 },
    buildings: { count: { min: 6, max: 12 }, types: ['house', 'shop', 'tower'], hasPlaza: false },
    nature: { treeDensity: 0.08, bushDensity: 0.1, flowerDensity: 0.04, rockDensity: 0.05 },
    npcs: { enabled: true, count: { min: 4, max: 8 } },
    groundType: 'grass',
  },
  'mexican-village': {
    id: 'mexican-village',
    name: 'Mexican Village',
    description: 'Adobe buildings, cacti, and vibrant colors',
    size: 'medium',
    theme: 'mexican',
    type: 'exterior',
    cols: { min: 50, max: 65 },
    rows: { min: 50, max: 65 },
    roads: { enabled: true, pattern: 'grid', width: 2 },
    water: { type: 'lake', coverage: 0.03 },
    buildings: { count: { min: 6, max: 12 }, types: ['house', 'shop', 'tower'], hasPlaza: true },
    nature: { treeDensity: 0.08, bushDensity: 0.15, flowerDensity: 0.08, rockDensity: 0.1 },
    npcs: { enabled: true, count: { min: 5, max: 10 } },
    groundType: 'sand',
  },
  'australian-outback': {
    id: 'australian-outback',
    name: 'Australian Outback',
    description: 'Red earth, eucalyptus, and desert terrain',
    size: 'large',
    theme: 'australian',
    type: 'exterior',
    cols: { min: 60, max: 80 },
    rows: { min: 60, max: 80 },
    roads: { enabled: true, pattern: 'winding', width: 2 },
    water: { type: 'lake', coverage: 0.03 },
    buildings: { count: { min: 3, max: 6 }, types: ['hut', 'house'], hasPlaza: false },
    nature: { treeDensity: 0.12, bushDensity: 0.15, flowerDensity: 0.02, rockDensity: 0.15 },
    npcs: { enabled: true, count: { min: 2, max: 5 } },
    groundType: 'sand',
  },
}

// Group presets by theme for UI
export const PRESET_CATEGORIES: Record<string, { label: string; color: string }> = {
  // Environment themes
  village: { label: 'Village/Town', color: 'bg-green-700' },
  forest: { label: 'Forest', color: 'bg-emerald-800' },
  castle: { label: 'Castle', color: 'bg-purple-700' },
  ice: { label: 'Ice/Snow', color: 'bg-cyan-700' },
  desert: { label: 'Desert', color: 'bg-amber-700' },
  dungeon: { label: 'Dungeon', color: 'bg-gray-700' },
  volcanic: { label: 'Volcanic', color: 'bg-red-800' },
  cave: { label: 'Cave', color: 'bg-stone-700' },
  crypt: { label: 'Crypt/Cemetery', color: 'bg-zinc-800' },
  underwater: { label: 'Underwater', color: 'bg-blue-800' },
  temple: { label: 'Temple', color: 'bg-teal-800' },
  // Cultural themes
  egyptian: { label: 'Egyptian', color: 'bg-yellow-700' },
  italian: { label: 'Italian', color: 'bg-orange-700' },
  chinese: { label: 'Chinese', color: 'bg-red-700' },
  spanish: { label: 'Spanish', color: 'bg-orange-600' },
  russian: { label: 'Russian', color: 'bg-red-900' },
  japanese: { label: 'Japanese', color: 'bg-pink-700' },
  african: { label: 'African', color: 'bg-amber-800' },
  venezuelan: { label: 'Venezuelan', color: 'bg-lime-700' },
  peruvian: { label: 'Peruvian', color: 'bg-stone-600' },
  argentinian: { label: 'Argentinian', color: 'bg-sky-700' },
  american: { label: 'American', color: 'bg-blue-700' },
  mexican: { label: 'Mexican', color: 'bg-rose-700' },
  australian: { label: 'Australian', color: 'bg-orange-800' },
}
