defmodule Nebulith.Catalog.BuildingCompositions do
  @moduledoc """
  Baked building COMPOSITIONS — a pre-built building (house/store/hospital/…) is a
  composition template stamped as per-cell tiles, exactly like a tree (MAP-MODEL §5,
  TILE-BACKEND-MIGRATION §4). NOT a procedural unit.

  Each entry is a footprint (`footprint_w` × `footprint_h`, south-facing) + one
  `composition_cells` row per stacked tile: `{dx, dy, level, label, walkable}`.
  Labels are wall/window/door/roof/roof_top. A cell's collision follows its ground
  block (a wall blocks; a door/interior is walkable), so every tile in a cell shares
  its walkability. Rotation to face a road happens at STAMP time (frontend), so only
  the south facing is stored.

  GENERATED, do not hand-edit: produced by baking the frontend render pipeline
  (composeBuilding → buildingCellTiles) once per (type,length) generation uses, so a
  stamped composition matches what the three views drew before buildings became data.
  """

  # Per-composition TYPE-SPECIFIC tiles. A store's blue roof, a hospital's green roof + white walls,
  # and per-house roof/wall variety are DISTINCT tiles (each carries its own colour in settings.colors)
  # — not a shared tile recoloured by a variant index. Only the labels listed here are remapped to a
  # type tile; everything else (big_house/temple/cathedral/castle, plus every door/window) keeps the
  # shared default tile, so those buildings stay unchanged. The type tiles are authored in
  # Nebulith.Catalog.TileSource.seed_building_tiles.
  @type_tiles %{
    "store_5" => %{"roof" => "roof_store", "roof_top" => "roof_top_store", "wall" => "wall_store"},
    "hospital_6" => %{
      "roof" => "roof_hospital",
      "roof_top" => "roof_top_hospital",
      "wall" => "wall_hospital"
    },
    "house_3" => %{
      "roof" => "roof_house_a",
      "roof_top" => "roof_top_house_a",
      "wall" => "wall_house_a"
    },
    "house_4" => %{
      "roof" => "roof_house_b",
      "roof_top" => "roof_top_house_b",
      "wall" => "wall_house_b"
    },
    "house_5" => %{
      "roof" => "roof_house_c",
      "roof_top" => "roof_top_house_c",
      "wall" => "wall_house_c"
    }
  }

  # A building's NAME → the apex badge the renderer draws (data for the signage). Only store/hospital
  # carry one; houses/others have none → no badge.
  @titles %{"store_5" => "Store", "hospital_6" => "Hospital"}

  @doc """
  Every baked building composition, keyed by type_length (hyphens in the type become underscores).

  Cells reference type-specific tiles (per `@type_tiles`) and store/hospital carry their apex-signage
  `title`, so the seeded compositions render each building's own colours + name.
  """
  def all do
    for {name, comp} <- definitions(), into: %{} do
      {name, comp |> remap_cells(name) |> put_title(name)}
    end
  end

  # Swap each cell's label for its type-specific tile (unlisted labels pass through unchanged).
  defp remap_cells(%{cells: cells} = comp, name) do
    overrides = Map.get(@type_tiles, name, %{})
    %{comp | cells: Enum.map(cells, fn c -> Map.update!(c, :label, &Map.get(overrides, &1, &1)) end)}
  end

  # Attach the apex-signage title when this building has one (store/hospital); leave it off otherwise.
  defp put_title(comp, name) do
    case Map.get(@titles, name) do
      nil -> comp
      title -> Map.put(comp, :title, title)
    end
  end

  # ── Composition BUILDER (spaced-window realism) ────────────────────────────
  # house/store/office are AUTHORED from a compact facade spec, not a hand-listed cell dump, so the
  # realism rule is explicit in code. Every building is the SAME shape: a perimeter WALL box whose
  # FRONT/BACK faces carry the door + a SPACED WINDOW GRID — window, wall, window … on EVEN columns,
  # vertically aligned across floors (never a solid band, never every cell) — capped by a roof (gable
  # or flat). Interior columns hold only the roof VOLUME so ISO reads a solid roof; 2D collapses depth
  # onto the front face (MAP-MODEL §2-3). The bigger civic buildings below stay hand-authored (out of
  # this sample pass).

  defp cell(dx, dy, level, label, walkable),
    do: %{dx: dx, dy: dy, level: level, label: label, walkable: walkable}

  # EVEN columns (0, 2, 4 …) are window columns → the spaced grid.
  defp window_col?(dx), do: rem(dx, 2) == 0

  defp perimeter?(dx, dy, w, h), do: dx == 0 or dx == w - 1 or dy == 0 or dy == h - 1

  # Build the wall box: for every PERIMETER cell, stack levels 0..wall_top labelled by `facade_fun`.
  # The door column is walkable end-to-end (you pass through the doorway); every other facade cell
  # blocks. Roof cells come from `roof_cells`.
  defp assemble(w, h, wall_top, door_col, facade_fun, roof_cells) do
    walls =
      for dy <- 0..(h - 1),
          dx <- 0..(w - 1),
          perimeter?(dx, dy, w, h),
          level <- 0..wall_top do
        cell(dx, dy, level, facade_fun.(dx, dy, level), dx == door_col)
      end

    %{footprint_w: w, footprint_h: h, cells: walls ++ roof_cells}
  end

  # A GABLE roof (houses): a triangular stack whose height per column falls off from the centre
  # (peak ≤3). Every column gets the eave course; inner columns rise to the ridge; the centre-back
  # apex is the `roof_top` cap. Perimeter roof caps block; the interior roof volume is walkable.
  defp gable_roof(w, h, wall_top) do
    center = (w - 1) / 2
    max_peak = min(3, div(w + 1, 2))
    eave = wall_top + 1
    door_col = div(w, 2)
    apex_col = div(w - 1, 2)

    for dy <- 0..(h - 1), dx <- 0..(w - 1), reduce: [] do
      acc ->
        levels = max(1, max_peak - trunc(Float.floor(abs(dx - center))))
        peri = perimeter?(dx, dy, w, h)

        cells =
          for i <- 0..(levels - 1) do
            apex = i == levels - 1 and dx == apex_col and dy == 0
            label = if apex, do: "roof_top", else: "roof"
            cell(dx, dy, eave + i, label, dx == door_col or not peri)
          end

        acc ++ cells
    end
  end

  # A FLAT roof (store/office): a parapet lip around the edge, a walkable deck inside, and one raised
  # detail block at the centre — the `roof_top` SIGN (badge anchor) for a titled shop, else a plain
  # `rooftop_unit` AC/vent block.
  defp flat_roof(w, h, wall_top, opts \\ []) do
    roof_level = wall_top + 1
    door_col = div(w, 2)

    deck =
      for dy <- 0..(h - 1), dx <- 0..(w - 1) do
        peri = perimeter?(dx, dy, w, h)
        label = if peri, do: "parapet", else: "flat_roof"
        cell(dx, dy, roof_level, label, dx == door_col or not peri)
      end

    crown_label = if opts[:title], do: "roof_top", else: "rooftop_unit"
    deck ++ [cell(div(w - 1, 2), div(h - 1, 2), roof_level + 1, crown_label, false)]
  end

  # HOUSE — 2 living floors + a gable roof. Windows sit on the upper course of each floor (levels 1 &
  # 3) on even columns; a 1×2 centred door spans the ground floor; a wall course separates the floors.
  defp house(w) do
    h = 4
    wall_top = 3
    door_col = div(w, 2)

    facade = fn dx, dy, level ->
      front_or_back = dy == 0 or dy == h - 1

      cond do
        dx == door_col and dy == h - 1 and level in [0, 1] -> "door"
        front_or_back and window_col?(dx) and level in [1, 3] -> "window"
        true -> "wall"
      end
    end

    assemble(w, h, wall_top, door_col, facade, gable_roof(w, h, wall_top))
  end

  # STORE — 5×4, 2 floors, flat roof. Ground FRONT = a storefront: a wide display window + centred
  # door + a striped awning band above it. Upper front = spaced windows. Back + sides are plain wall.
  defp store do
    w = 5
    h = 4
    wall_top = 3
    door_col = div(w, 2)

    facade = fn dx, dy, level ->
      front = dy == h - 1

      cond do
        front and dx == door_col and level in [0, 1] -> "door"
        front and level == 0 -> "display_window"
        front and level == 1 -> "awning"
        front and level == 3 and window_col?(dx) -> "window"
        true -> "wall"
      end
    end

    assemble(w, h, wall_top, door_col, facade, flat_roof(w, h, wall_top, title: true))
  end

  # OFFICE / APARTMENT — 5×5, 3 floors, flat roof. A regular spaced window GRID (even columns × every
  # floor, aligned), a 1×2 centred door, a small rooftop unit. Taller than a house or store.
  defp office do
    w = 5
    h = 5
    wall_top = 5
    door_col = div(w, 2)

    facade = fn dx, dy, level ->
      front_or_back = dy == 0 or dy == h - 1

      cond do
        dx == door_col and dy == h - 1 and level in [0, 1] -> "door"
        front_or_back and window_col?(dx) and level in [1, 3, 5] -> "window"
        true -> "wall"
      end
    end

    assemble(w, h, wall_top, door_col, facade, flat_roof(w, h, wall_top))
  end

  defp definitions do
    Map.merge(large_buildings(), %{
      "house_3" => house(3),
      "house_4" => house(4),
      "house_5" => house(5),
      "store_5" => store(),
      "office_5" => office()
    })
  end

  # The larger civic buildings stay hand-authored (unchanged this pass).
  defp large_buildings do
%{
      "big_house_6" => %{
        footprint_w: 6,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "roof_top", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 2, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 3, label: "window", walkable: true},
          %{dx: 3, dy: 3, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 4, label: "roof", walkable: false}
        ]
      },
      "hospital_6" => %{
        footprint_w: 6,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "roof_top", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 2, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 3, label: "window", walkable: true},
          %{dx: 3, dy: 3, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 4, label: "roof", walkable: false}
        ]
      },
      "temple_8" => %{
        footprint_w: 8,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 7, label: "roof_top", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 7, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 7, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 6, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 7, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 6, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 4, dy: 3, level: 2, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 3, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 4, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 5, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 7, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 6, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 7, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 6, label: "roof", walkable: false}
        ]
      },
      "cathedral_7" => %{
        footprint_w: 7,
        footprint_h: 5,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 6, label: "roof_top", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 1, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 2, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 1, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 4, level: 0, label: "door", walkable: true},
          %{dx: 3, dy: 4, level: 1, label: "wall", walkable: true},
          %{dx: 3, dy: 4, level: 2, label: "wall", walkable: true},
          %{dx: 3, dy: 4, level: 3, label: "wall", walkable: true},
          %{dx: 3, dy: 4, level: 4, label: "window", walkable: true},
          %{dx: 3, dy: 4, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 4, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 4, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 4, level: 5, label: "roof", walkable: false}
        ]
      },
      "castle_12" => %{
        footprint_w: 12,
        footprint_h: 6,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 10, label: "roof_top", walkable: false},
          %{dx: 6, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 7, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 7, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 8, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 8, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 8, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 8, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 8, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 9, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 9, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 9, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 9, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 9, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 10, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 10, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 10, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 10, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 11, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 1, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 1, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 2, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 2, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 3, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 3, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 4, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 4, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 1, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 2, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 3, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 3, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 3, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 4, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 4, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 4, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 4, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 5, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 5, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 5, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 6, dy: 5, level: 0, label: "door", walkable: true},
          %{dx: 6, dy: 5, level: 1, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 2, label: "window", walkable: true},
          %{dx: 6, dy: 5, level: 3, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 4, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 5, label: "window", walkable: true},
          %{dx: 6, dy: 5, level: 6, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 7, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 8, label: "window", walkable: true},
          %{dx: 6, dy: 5, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 5, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 7, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 7, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 8, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 8, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 8, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 8, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 8, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 9, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 9, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 9, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 9, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 9, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 10, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 10, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 10, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 10, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 11, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 5, level: 9, label: "roof", walkable: false}
        ]
      }
    }
  end
end

