defmodule Nebulith.Catalog.BuildingCompositions do
  @moduledoc """
  Baked building COMPOSITIONS — a pre-built building (house/store/hospital/…) is a
  composition template stamped as per-cell tiles, exactly like a tree (MAP-MODEL §5,
  TILE-BACKEND-MIGRATION §4). NOT a procedural unit.

  Each entry is a footprint (`footprint_w` × `footprint_h`, south-facing) + one
  `composition_cells` row per stacked tile: `{dx, dy, level, label, walkable}`.
  Labels are wall/window/door/roof/roof_top. A cell's collision follows its ground
  block (a wall blocks; a door/interior is walkable), so every tile in a cell shares
  its walkability. Rotation to face a road happens at STAMP time (frontend), so only
  the south facing is stored.

  GENERATED, do not hand-edit: produced by baking the frontend render pipeline
  (composeBuilding → buildingCellTiles) once per (type,length) generation uses, so a
  stamped composition matches what the three views drew before buildings became data.
  """

  # Per-composition TYPE-SPECIFIC tiles. A store's blue roof, a hospital's green roof + white walls,
  # and per-house roof/wall variety are DISTINCT tiles (each carries its own colour in settings.colors)
  # — not a shared tile recoloured by a variant index. Only the labels listed here are remapped to a
  # type tile; everything else (big_house/temple/cathedral/castle, plus every door/window) keeps the
  # shared default tile, so those buildings stay unchanged. The type tiles are authored in
  # Nebulith.Catalog.TileSource.seed_building_tiles.
  @type_tiles %{
    "store_5" => %{"roof" => "roof_store", "roof_top" => "roof_top_store", "wall" => "wall_store"},
    "hospital_6" => %{
      "roof" => "roof_hospital",
      "roof_top" => "roof_top_hospital",
      "wall" => "wall_hospital"
    },
    "house_3" => %{
      "roof" => "roof_house_a",
      "roof_top" => "roof_top_house_a",
      "wall" => "wall_house_a"
    },
    "house_4" => %{
      "roof" => "roof_house_b",
      "roof_top" => "roof_top_house_b",
      "wall" => "wall_house_b"
    },
    "house_5" => %{
      "roof" => "roof_house_c",
      "roof_top" => "roof_top_house_c",
      "wall" => "wall_house_c"
    }
  }

  # A building's NAME → the apex badge the renderer draws (data for the signage). Only store/hospital
  # carry one; houses/others have none → no badge.
  @titles %{"store_5" => "Store", "hospital_6" => "Hospital"}

  @doc """
  Every baked building composition, keyed by type_length (hyphens in the type become underscores).

  Cells reference type-specific tiles (per `@type_tiles`) and store/hospital carry their apex-signage
  `title`, so the seeded compositions render each building's own colours + name.
  """
  def all do
    for {name, comp} <- definitions(), into: %{} do
      {name, comp |> remap_cells(name) |> put_title(name)}
    end
  end

  # Swap each cell's label for its type-specific tile (unlisted labels pass through unchanged).
  defp remap_cells(%{cells: cells} = comp, name) do
    overrides = Map.get(@type_tiles, name, %{})
    %{comp | cells: Enum.map(cells, fn c -> Map.update!(c, :label, &Map.get(overrides, &1, &1)) end)}
  end

  # Attach the apex-signage title when this building has one (store/hospital); leave it off otherwise.
  defp put_title(comp, name) do
    case Map.get(@titles, name) do
      nil -> comp
      title -> Map.put(comp, :title, title)
    end
  end

  defp definitions do
%{
      "house_3" => %{
        footprint_w: 3,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "roof_top", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 2, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 1, level: 2, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 2, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 2, level: 2, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 1, dy: 3, level: 2, label: "roof", walkable: true},
          %{dx: 1, dy: 3, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 2, label: "roof", walkable: false}
        ]
      },
      "house_4" => %{
        footprint_w: 4,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "roof_top", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 1, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 2, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 2, dy: 3, level: 2, label: "window", walkable: true},
          %{dx: 2, dy: 3, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 3, label: "roof", walkable: false}
        ]
      },
      "house_5" => %{
        footprint_w: 5,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "roof_top", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 1, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 2, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 2, dy: 3, level: 2, label: "window", walkable: true},
          %{dx: 2, dy: 3, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 3, level: 3, label: "roof", walkable: false}
        ]
      },
      "big_house_6" => %{
        footprint_w: 6,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "roof_top", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 2, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 3, label: "window", walkable: true},
          %{dx: 3, dy: 3, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 4, label: "roof", walkable: false}
        ]
      },
      "store_5" => %{
        footprint_w: 5,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "roof_top", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 3, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 1, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 3, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 2, level: 3, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 2, dy: 3, level: 2, label: "window", walkable: true},
          %{dx: 2, dy: 3, level: 3, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 3, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 3, level: 3, label: "roof", walkable: false}
        ]
      },
      "hospital_6" => %{
        footprint_w: 6,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "roof_top", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 1, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 4, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 2, level: 4, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 2, label: "wall", walkable: true},
          %{dx: 3, dy: 3, level: 3, label: "window", walkable: true},
          %{dx: 3, dy: 3, level: 4, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 3, level: 4, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 4, label: "roof", walkable: false}
        ]
      },
      "temple_8" => %{
        footprint_w: 8,
        footprint_h: 4,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 7, label: "roof_top", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 7, label: "roof", walkable: false},
          %{dx: 7, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 7, label: "roof", walkable: true},
          %{dx: 7, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 1, level: 6, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 7, label: "roof", walkable: true},
          %{dx: 7, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 2, level: 6, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 4, dy: 3, level: 0, label: "door", walkable: true},
          %{dx: 4, dy: 3, level: 1, label: "wall", walkable: true},
          %{dx: 4, dy: 3, level: 2, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 3, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 4, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 5, label: "window", walkable: true},
          %{dx: 4, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 7, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 6, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 3, level: 7, label: "roof", walkable: false},
          %{dx: 7, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 3, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 3, level: 6, label: "roof", walkable: false}
        ]
      },
      "cathedral_7" => %{
        footprint_w: 7,
        footprint_h: 5,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 6, label: "roof_top", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 1, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 1, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 1, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 1, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 2, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 2, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 1, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 5, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 6, label: "roof", walkable: true},
          %{dx: 6, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 3, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 3, level: 5, label: "roof", walkable: false},
          %{dx: 0, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 1, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 1, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 2, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 2, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 2, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 3, dy: 4, level: 0, label: "door", walkable: true},
          %{dx: 3, dy: 4, level: 1, label: "wall", walkable: true},
          %{dx: 3, dy: 4, level: 2, label: "wall", walkable: true},
          %{dx: 3, dy: 4, level: 3, label: "wall", walkable: true},
          %{dx: 3, dy: 4, level: 4, label: "window", walkable: true},
          %{dx: 3, dy: 4, level: 5, label: "roof", walkable: true},
          %{dx: 3, dy: 4, level: 6, label: "roof", walkable: true},
          %{dx: 4, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 4, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 4, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 5, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 5, dy: 4, level: 5, label: "roof", walkable: false},
          %{dx: 5, dy: 4, level: 6, label: "roof", walkable: false},
          %{dx: 6, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 2, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 4, level: 4, label: "window", walkable: false},
          %{dx: 6, dy: 4, level: 5, label: "roof", walkable: false}
        ]
      },
      "castle_12" => %{
        footprint_w: 12,
        footprint_h: 6,
        cells: [
          %{dx: 0, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 1, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 1, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 2, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 2, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 3, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 3, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 3, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 4, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 4, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 4, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 5, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 5, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 5, dy: 0, level: 10, label: "roof_top", walkable: false},
          %{dx: 6, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 6, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 6, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 6, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 7, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 7, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 7, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 7, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 8, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 8, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 8, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 8, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 8, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 8, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 9, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 9, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 9, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 9, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 9, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 9, dy: 0, level: 10, label: "roof", walkable: false},
          %{dx: 10, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 10, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 10, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 10, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 10, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 11, dy: 0, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 0, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 0, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 0, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 0, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 1, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 1, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 1, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 1, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 1, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 1, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 1, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 1, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 1, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 2, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 2, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 2, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 2, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 2, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 2, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 2, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 2, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 2, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 3, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 3, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 3, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 3, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 3, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 3, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 3, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 3, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 3, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 4, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 4, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 2, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 3, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 3, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 4, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 4, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 5, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 5, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 6, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 7, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 8, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 8, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 9, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 9, dy: 4, level: 10, label: "roof", walkable: true},
          %{dx: 10, dy: 4, level: 9, label: "roof", walkable: true},
          %{dx: 11, dy: 4, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 4, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 4, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 4, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 4, level: 9, label: "roof", walkable: false},
          %{dx: 0, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 0, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 0, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 0, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 0, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 1, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 1, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 1, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 1, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 1, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 2, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 2, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 2, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 2, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 2, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 3, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 3, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 3, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 3, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 3, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 3, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 4, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 4, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 4, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 4, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 4, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 4, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 5, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 5, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 5, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 5, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 5, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 5, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 6, dy: 5, level: 0, label: "door", walkable: true},
          %{dx: 6, dy: 5, level: 1, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 2, label: "window", walkable: true},
          %{dx: 6, dy: 5, level: 3, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 4, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 5, label: "window", walkable: true},
          %{dx: 6, dy: 5, level: 6, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 7, label: "wall", walkable: true},
          %{dx: 6, dy: 5, level: 8, label: "window", walkable: true},
          %{dx: 6, dy: 5, level: 9, label: "roof", walkable: true},
          %{dx: 6, dy: 5, level: 10, label: "roof", walkable: true},
          %{dx: 7, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 7, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 7, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 7, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 7, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 7, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 8, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 8, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 8, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 8, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 8, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 8, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 9, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 9, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 9, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 9, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 9, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 9, dy: 5, level: 10, label: "roof", walkable: false},
          %{dx: 10, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 10, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 10, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 10, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 10, dy: 5, level: 9, label: "roof", walkable: false},
          %{dx: 11, dy: 5, level: 0, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 1, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 2, label: "window", walkable: false},
          %{dx: 11, dy: 5, level: 3, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 4, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 5, label: "window", walkable: false},
          %{dx: 11, dy: 5, level: 6, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 7, label: "wall", walkable: false},
          %{dx: 11, dy: 5, level: 8, label: "window", walkable: false},
          %{dx: 11, dy: 5, level: 9, label: "roof", walkable: false}
        ]
      }
    }
  end
end

