import { chromium } from 'playwright'
const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1680,height:1000}})
const errs = []; const bad = []
p.on('pageerror', e => errs.push(e.message))
p.on('response', r => { if (r.status() >= 400) bad.push(r.status() + ' ' + r.url()) })
await p.goto('http://localhost:3000/personal-projects/game-engine/games/97829bd2-78fa-4d8f-94aa-8d0cea5f8ffb', {waitUntil:'networkidle', timeout:60000})
await p.waitForTimeout(5000)
await p.locator('.z-rail button', { hasText: 'Player UI' }).click(); await p.waitForTimeout(1200)
console.log('grid areas  :', await p.evaluate(() => getComputedStyle(document.querySelector('main')).gridTemplateAreas))
console.log('inspector   :', await p.locator('.z-insp').count(), '(0 = dropped, as designed)')
console.log('HUD pieces  :', await p.locator('.hel').count(), '| with real content:', await p.locator('.hel .hbody > *').count())
console.log('stage label :', await p.locator('.hscale').textContent().catch(()=>'—'))
console.log('overlaps    :', await p.locator('.z-panel .warn').count(), 'warning blocks')
const before = await p.locator('.z-panel input').first().inputValue().catch(()=>'?')
const box = await p.locator('.hel[data-k="quest_tracker"]').boundingBox()
await p.mouse.move(box.x + box.width/2, box.y + box.height/2); await p.mouse.down()
await p.mouse.move(box.x + box.width/2 + 90, box.y + box.height/2 + 60, { steps: 10 }); await p.waitForTimeout(300)
await p.mouse.up(); await p.waitForTimeout(300)
console.log('drag → selected:', await p.evaluate(() => document.querySelector('.hel.sel')?.getAttribute('data-k')))
console.log('panel numbers followed:', await p.locator('.z-panel .ctl input[type=number]').first().inputValue().catch(()=>'—'))
await p.screenshot({ path: process.argv[2] + '/app-03-playerui.png' })
console.log('page errors:', errs.length ? errs.slice(0,3) : 'none')
console.log('HTTP failures:', bad.length ? bad.slice(0,3) : 'none')
await b.close()
